apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-eval
  labels:
    app: user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: mysql-container
          image: datascientest/mysql-k8s:1.0.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: Main
          ports:
            - containerPort: 3306

        - name: fastapi-container
          image: gnembac/fastapi-k8s:1.0.1
          env:
            - name: MYSQL_URL
              value: mysql-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: Main
          ports:
            - containerPort: 8000